### ISSUE TITLE
Nice big blue Download button 

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#10]
.. to supplant the 'Get it on Play and 'Get it on Github' buttons, just a big 'Download' button and perhaps that page can eventually detect the device's OS and recommend the appropriate client:

- Android
- Windows
- Linux
- Mac (coming soon!)

**Comment by jnny** [comment]
Like this one:
![image](https://github.com/willow446/willow446.github.io/assets/1790886/a70fc0fc-b695-47aa-bae5-88f4cc5e5368)

**Comment by willow446** [comment]
Is this just for the mobile version? On desktop we have a download button that sits in the nav bar.

**Comment by jnny** [comment]
It's just that I want to highlight being cross-platform and reduce clutter on the homepage. Both [Signal](https://signal.org) and [Tor](https://torproject.org) have similar flows, for example...

This also leaves more room for adding signature verification files and info. Maybe we can just swipe these icons straight from the Tor site? :)

![image](https://github.com/willow446/willow446.github.io/assets/1790886/d342db20-0ec8-4fbd-be14-cfece59d8f9c)

**Comment by willow446** [comment]
To clarify before I go implement: move the individual download links to a /download page (and add space for hashes etc) and replace the current badges with a "Get Ouisync" button on the home screen?

**Comment by jnny** [comment]
See PR #13
