### ISSUE TITLE
Vertical top spacing for headers

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#11]
Headers in the css need to have some vertical top spacing - see examples below:

![image](https://github.com/willow446/willow446.github.io/assets/1790886/4a34cfa5-703e-4f6a-bc0d-7b8ef35f6b9a)

![image](https://github.com/willow446/willow446.github.io/assets/1790886/ada8c672-a9d8-4ac7-80e9-c2e10c20f607)

**Comment by willow446** [comment]
I still need to improve the overall typography of the markdown sections, but this specific issue was addressed as part of e807c6edeb4cc224cee636faa7c58214e2a6ef0a

**Comment by jnny** [comment]
Much better!
Tiny nitpick but can we make the bottom vertical spacing lesser than the top? For subheaders at least (###, ####):

Seems it is this way for higher-level headers but not for sub?

![image](https://github.com/willow446/willow446.github.io/assets/1790886/6ba7db2c-1bd5-432e-94fe-e73aeb5994c1)

**Comment by jnny** [comment]
Fixed in a recent commit
