### ISSUE TITLE
Background shade for FAQ dropdowns

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#16]
I was thinking that I didn't like the borders around each question, but I think really I just don't like the black and white-ness of the whole page. What about a very light violet or blue within our brand palette inside those boxes? Ensure it doesn't mess with a11y contrast..

**Comment by jnny** [comment]
Might also look nicer with more narrow margin (eg filling 75% of the page instead of nearly 100), but would have to play with this on different screen sizes..

This is also related to #12 generally.

**Comment by willow446** [comment]
Yeah shorter widths on text sections are usually a lot easier to read, I'll experiment with this and see what I come up with.

**Comment by jnny** [comment]
I just added drop shadows to the screenshots which looks nicer...

I think the current margins are now too narrow - let's widen by 25% or so?

**Comment by willow446** [comment]
The drop shadows and new sizing for the images look great. @jnny did you already widen the margins?
If so do you think this issue is ready to close?

**Comment by jnny** [comment]
Yay, yes and yes :)
