### ISSUE TITLE
Create Community page

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#20]
We can follow a similar format as Ceno's:  https://censorship.no/en/help.html

- Translations: https://hosted.weblate.org/projects/ouisync/
- Maybe replace User Research' with Events and add a blurb about the Internet Without Borders hackathong - https://internetborders.net
- Source Code and link to:
 - https://github.com/equalitie/ouisync
 - https://github.com/equalitie/ouisync-app
 - https://github.com/equalitie/ouisync-plugin

If you could tee up the layout @willow446 I'll work on the content!

**Comment by willow446** [comment]
I'll ping you when I finish the layout :+1:

**Comment by jnny** [comment]
Nice, I updated the content, icons, and added some things to the CSS community-cards file..

**Comment by jnny** [comment]
This page looks solid to me, but feel welcome to reopen if you feel something is missing @IvanaBlvzc
