### ISSUE TITLE
Title and subtitle on top of the home page need to be updated?

### ISSUE THREAD

**Issue by IvanaBlzvc** [willow446/willow446.github.io#24]
https://willow446.github.io/
![Screenshot 2023-07-17 at 12 14 59](https://github.com/willow446/willow446.github.io/assets/121942562/b4ea8679-a6b0-41d0-9c1d-b737ae763df5)
https://mattermost.equalit.ie/equalitie/pl/aew9txjws38ddb73uxipp5fs5h
D's suggestion "Ouisync is a privacy and connectivity focused solution for synchronizing files and folders with your devices, contacts and groups."
K's suggestion "Ouisync is a private and resilient solution for syncing files and folders with your devices, contacts and groups"?

**Comment by jnny** [comment]
Those suggestions were for [the About page](https://willow446.github.io/about/) and have been incorporated

**Comment by willow446** [comment]
Closing this for now, please feel free to reopen if there's work still to be done on the home page hero text.
