### ISSUE TITLE
Website: Include the roadmap 

### ISSUE THREAD

**Issue by IvanaBlzvc** [willow446/willow446.github.io#25]
Possibly replace the team with ouisync roadmap - which needs to be in sync with the planned deliverables for the next grant period and with the miro board + roadmap published to github (which is a pending task for ouisync team from before)
https://willow446.github.io/about/

**Comment by willow446** [comment]
Hi, I'm not sure if this was posted before the content was added, but there is a roadmap section on the current About page? If there's any modifications or additions you would like to make feel free to use this ticket to track that.

**Comment by willow446** [comment]
Ignore this commit ^^^ I accidentally tagged this issue instead of issue number 23

**Comment by jnny** [comment]
Right, I added this last week:
![image](https://github.com/willow446/willow446.github.io/assets/1790886/9acf2b2e-0222-4f64-afd8-8ac72898b8bd)
