### ISSUE TITLE
Add Security page

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#26]
Waiting on text from Ksenia, but we could tee it up in the meantime. It will be linked to on the homepage third section column 1 and in the FAQ (TODO).

**Comment by willow446** [comment]
added as a blank content page in fc877b4f4687ddca3c786cd5607ddf9bceb1640b
Feel free to drop the text here or in the ouisync channel :+1:

**Comment by jnny** [comment]
Added in latest commit - need to rebuild site

**Comment by jnny** [comment]
So it's there - https://willow446.github.io/security/ - but doesn't look especially nice. I'm wondering if we should just put it in the FAQ accordion, set an anchor and make that the link from the homepage?

**Comment by willow446** [comment]
What visual changes would you make to make it look nicer? Maybe we can just update the single page hugo template to make all "blog post" type pages look nicer.

**Comment by willow446** [comment]
Possibly related to #12

**Comment by jnny** [comment]
Yes this is more relevant to #12, so closing for now :)
