### ISSUE TITLE
Support RTL Layouts

### ISSUE THREAD

**Issue by willow446** [willow446/willow446.github.io#35]
Done using the `languageDirection` variable in hugo

**Comment by jnny** [comment]
is this set in the config.toml file?

**Comment by willow446** [comment]
@jnny we set which languages are RTL in the config file, then use the hugo direction variable to toggle between CSS classes in the html code. 
By design I used the RTL-friendly CSS classes (eg padding-inline-start instead of padding-inline-left) when writing everything so adding this should not require significant work to shift the layouts for RTL languages.

**Comment by willow446** [comment]
This was completed in eaa2ca5b5fe58d7cb9dfd0ff177dba648673d86e
