### ISSUE TITLE
Enlarge text size in third section

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#6]
Ideally should match the font size of the middle section..

**Comment by willow446** [comment]
done in 19c19a8ee3c5036d11ce4ddc6e9e958c6dc65bc1

**Comment by jnny** [comment]
Nice to wake up to this! :) Reopening (sorry) because I like this text size in general and think the normal paragraph text size is still to small (see the footer and FAQ text on desktop especially) - can we bump it up a notch?

**Comment by willow446** [comment]
do you want all the paragraphs to be the size in the 2nd and 3rd sections? I have a patch rn to do that if you want.

**Comment by jnny** [comment]
Much more readable, thank you!!
