### ISSUE TITLE
Bump footer icons to the right

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#7]
...aligned with the eQ logo, ideally (on desktop - fine to stack on mobile)

**Comment by willow446** [comment]
done in 0022dab4b557fdda6a445b4b845dbb5e71d27b46

It looks so much better, but I think one potential issue is that the alignment slightly visually groups the icons with eQ's logo, maybe leading site visitors to think the links are for eQ. That's the only thing I'd consider.

I don't know a way of getting around this while making it look visually as nice though :sweat_smile:

**Comment by jnny** [comment]
Very nice! I will make the icons ouisync-purple, that should solve it!

**Comment by willow446** [comment]
Awesome, great idea! Closing now because I'm happy with this implementation.
