### ISSUE TITLE
Could we get a beautiful footer separator?

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#8]
![image](https://github.com/willow446/willow446.github.io/assets/1790886/a35db1f8-3105-4039-b760-35bb56305fff)

Below the drop - wondering how we could add a separator bar above the footer that transitions from the blue to the purple..

**Comment by willow446** [comment]
Does this work: https://willow446.github.io/faq/

**Comment by jnny** [comment]
Nice! Looks great! \o/
