### ISSUE TITLE
Differentiate hyperlinks

### ISSUE THREAD

**Issue by jnny** [willow446/willow446.github.io#9]
I'm a fan of blue but no underline..

**Comment by willow446** [comment]
Do you just want the underline removed on hover, or do you want the underline removed on hover + have the blue shown regardless of hover to differentiate links from normal text?

**Comment by jnny** [comment]
No underline - maybe just a slight effect?
`text-decoration: none;
touch-action: manipulation`

**Comment by jnny** [comment]
and no color differentiation, i mean - the subtle change on hover should be sufficient (to eg a dark gray text)

**Comment by jnny** [comment]
I removed the underlining but kept the color
